

pipeline {
    agent any
    
    
      tools {
        maven 'apache-maven-3.6.1' 
    }

    stages {
        stage('build') {
            steps {
                echo 'Compiling worket app'
                dir('worker') {
                    sh 'mvn compile'

                }
                
            }
        } 
        stage('test') {
            steps {
                echo 'Running Unit Test on worker app'
                
            }
        } 
        stage('package') {
            steps {
                echo 'Packaging worket app'
                
            }
        }
    }
    post {
        always {
            echo 'Build pipeline for worker run is complete..'
        }
        }   
    
    
}
