

pipeline {
    agent any
    
    
      tools {
        maven 'Maven 3.6.1' 
    }

    stages {
        stage('build') {

            steps {
                echo 'Compiling worket app'
                dir('worker') {
                    sh 'mvn compile'

                }
                
            }
        } 
        stage('test') {

            when {
                branch 'master'
                changeset "**/worket/**"
            }
            steps {
                echo 'Running Unit Test on worker app'
                
            }
        } 
        stage('package') {
            when {
                branch 'master'
                changeset "**/worket/**"
            }
            steps {
                echo 'Packaging worket app'
                
            }
        }
    }
    post {
        always {
            echo 'Build pipeline for worker run is complete..'
        }
        failure {
            slackSend (channel: "instavote-cd", message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL} | Open>)")
        }

        success {
            slackSend (channel: "instavote-cd", message: "Build Succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL} | Open>)")
        }



        }   
    
    
}
