

pipeline {
    agent any
    
    
      tools {
        maven 'Maven 3.6.1' 
    }

    stages {
        stage('build') {
            when {
                branch 'master'
                changeset "**/worket/**"
            }
            steps {
                echo 'Compiling worket app'
                dir('worker') {
                    sh 'mvn compile'

                }
                
            }
        } 
        stage('test') {

            when {
                branch 'master'
                changeset "**/worket/**"
            }
            steps {
                echo 'Running Unit Test on worker app'
                
            }
        } 
        stage('package') {
            when {
                branch 'master'
                changeset "**/worket/**"
            }
            steps {
                echo 'Packaging worket app'
                
            }
        }
    }
    post {
        always {
            echo 'Build pipeline for worker run is complete..'
        }
        }   
    
    
}
